version: '3'
services:
  nginx:
    build: ./conf/nginx
    ports:
      - ${NGINX_BACKEND_PORT}:80
      - ${NGINX_MIDDLE_PORT}:84
    volumes:
      - ${APPLICATION}:/var/www/html:rw
      - ${LOG_PATH}:/var/log/nginx:rw
      - ${NGINX_VHOST_PATH}:/etc/nginx/conf.d/:ro
      - ${NGINX_CONFIG_FILENAME}:/etc/nginx/nginx.conf:rw
    restart: always
    command: nginx -g 'daemon off;'
    networks:
      - webnet

  php-fpm:
    build: ./conf/php/
    ports:
      - ${PHPFPM_PORT}:9000
    volumes:
      - ${APPLICATION}/backend:/var/www/html:rw
      - ${LOG_PATH}:/var/log:rw
      - ${PHP_INI_PATH}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_PATH}:/usr/local/etc/php-fpm.d/www.conf:rw
    restart: always
    networks:
      - webnet

  node:
    build: ./conf/node/
    ports:
      - ${NODE_DEV_PORT}:9527
    volumes:
      - ${APPLICATION}/middle:/srv:rw
    tty: true
    networks:
      - webnet

  mysql:
    build: ./conf/mysql
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql/:rw
      - ${LOG_PATH}:/var/lib/mysql-logs:rw
      - ${MYSQL_CONFIG_FILENAME}:/etc/mysql/conf.d/mysql.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always
    networks:
      - webnet

  phpmyadmin:
    build: ./conf/phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: mysql
    restart: always
    networks:
      - webnet

  redis:
    build: ./conf/redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_CONFIG_FILENAME}:/usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - webnet

networks:
  webnet: